---
title: "More Visualizations in R"
author: "David Fong"
date: "4th April 2019"
output: html_document
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(reshape2)
```

*exercise for "The Analytics Edge" MITx*

## data

International students at MIT

```{r cars}
intl <- read.csv("intl.csv")
str(intl)
```

## Plots

```{r}

intl <- transform(intl, Region = reorder(Region, -PercentOfIntl))
 # re-orer regions according to declining PercentOfIntl

intl$PercentOfIntl <- intl$PercentOfIntl * 100

ggplot(intl, aes(x = Region, y = PercentOfIntl)) + 
  geom_bar(stat = "identity", fill = "dark blue") +   
   # 'identity' use the value of the 'y' variable 'as is'
  geom_text(aes(label = PercentOfIntl), vjust = -0.4) +
   # vjust moves labels up
  ylab("Percent of international students") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) # angle text and move horizontally
  
```


```{r}
intlall <- read.csv("intlall.csv", stringsAsFactors = FALSE)
str(intlall)
```

Country, undergraduates, graduates, special undergraduates, special graduates, exchange or visiting and total

*NA* is actually 'zero'

```{r}
intlall[is.na(intlall)] <- 0

world_map <- map_data("world")
str(world_map)
```

Each 'group' is actually the country. 'region' is the country name.

```{r}
intlall$Citizenship[intlall$Citizenship == "China (People's Republic Of)"] <-"China"
 # some countries need to be renamed for a subsequent match to occur

world_map <- merge(world_map, intlall, by.x = "region", by.y = "Citizenship")

world_map <- world_map[order(world_map$group, world_map$order),]
 # needs to be ordered by 'order' of polygon points, as well as by country
```

```{r}
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Total), color = "black") +
  coord_map("mercator", xlim = c(-180, 180)) # xlim required to remove some extraneous points!
  
```

```{r}
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Total), color = "black") +
  coord_map("ortho", orientation = (c(20, 30, 0)))
  
```

```{r}
households <- read.csv("households.csv")
str(households)
```

A year column, and then six other columns for each of the different household types.

```{r}
households[, 1:2]
```

```{r}
head(reshape2::melt(households, id = "Year"))
```

```{r}
ggplot(melt(households, id = "Year"), 
       aes(x = Year, y = value, color = variable)) +
  geom_line(size = 2) + geom_point(size = 5) + ylab("percentage of Households")
```








